#
# Copyright (C) 2023 AuxXxilium <https://github.com/AuxXxilium> and Ing <https://github.com/wjz304>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: Build SunComp Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: "format %y.%-m.$i or auto"
        required: false
        type: string
      notice:
        description: "Notice here"
        required: false
        type: string
      prerelease:
        description: "pre release"
        default: false
        type: boolean
      clean:
        description: "clean"
        default: false
        type: boolean
      addons_version:
        description: "addons version"
        default: ""
        type: string
      configs_version:
        description: "configs version"
        default: ""
        type: string
      modules_version:
        description: "modules version"
        default: ""
        type: string
      lkm_version:
        description: "lkm version"
        default: ""
        type: string
      patches_version:
        description: "patches version"
        default: ""
        type: string
      theme_version:
        description: "theme version"
        default: ""
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Clean Old
        if: inputs.clean == true
        uses: Nats-ji/delete-old-releases@v1
        with:
          token: ${{ secrets.SUN_GITHUB_TOKEN }}
          keep-count: 10
          keep-old-minor-releases: false

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          swap-storage: false

      # Install Dependencies
      - name: Install Dependencies
        run: |
          git config --global user.email "jadavdilip007@gmail.com"
          git config --global user.name "dj-devops-guru"
          sudo timedatectl set-timezone "Asia/Calcutta"

          sudo apt update
          sudo apt install -y jq gawk cpio gettext libelf-dev busybox dialog curl sed 
          sudo snap install yq

      # calculates the version number and push
      - name: Calculate Version
        run: |
          # Calculate Version
          VERSION=""
          if [ -n "${{ inputs.version }}" ]; then
            VERSION="${{ inputs.version }}"
          else
            LATEST_TAG="$(curl -skL "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r ".tag_name" 2>/dev/null)"
            if [[ -n "${LATEST_TAG}" && "`echo ${LATEST_TAG} | cut -d '.' -f 1,2`" = "`date +'%y.%-m.%-d'`" ]]; then  # format %y.%-m.$i
              VERSION="`echo ${LATEST_TAG} | awk -F '.' '{$3=$3+1}1' OFS='.'`"
            else
              VERSION="`date +'%y.%-m.%-d'`"
            fi
          fi
          
          echo "Version: ${VERSION}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

          if [ -n "${VERSION}" ]; then
            # Modify Source File
            echo "${VERSION}" >VERSION
            echo "${VERSION}" >files/p1/ARC-VERSION
            sed 's/^ARC_VERSION=.*/ARC_VERSION="'${VERSION}'"/' -i files/initrd/opt/arc/include/consts.sh
          fi

      # Get extractor, LKM, Addons, Modules, Theme and Configs
      - name: Get extractor, LKM, Addons, Modules, Theme and Configs
        run: |
          . scripts/func.sh

          LKMTAG="${{ inputs.lkm_version }}"
          getLKMs "files/p3/lkms"
          echo "LKMTAG=${TAG}" >> $GITHUB_ENV
          ADDONSTAG="${{ inputs.addons_version }}"
          getAddons "files/p3/addons"
          echo "ADDONSTAG=${TAG}" >> $GITHUB_ENV
          MODULESTAG="${{ inputs.modules_version }}"
          getModules "files/p3/modules"
          echo "MODULESTAG=${TAG}" >> $GITHUB_ENV
          CONFIGSTAG="${{ inputs.configs_version }}"
          getConfigs "files/p3/configs"
          echo "CONFIGSTAG=${TAG}" >> $GITHUB_ENV
          PATCHESTAG="${{ inputs.patches_version }}"
          getPatches "files/p3/patches"
          echo "PATCHESTAG=${TAG}" >> $GITHUB_ENV
          THEMETAG="${{ inputs.theme_version }}"
          getTheme "files/p1/boot/grub"
          echo "THEMETAG=${TAG}" >> $GITHUB_ENV
          getOffline "files/p3/configs"
          echo "Get Buildroot"
          getBuildroot "latest" "br"
          echo "BR_VERSION=${TAG}" >> $GITHUB_ENV
          echo "BUILD_TIME=$(date +'%Y-%m-%d %H:%M')" >> $GITHUB_ENV

          echo "OK"

      # Build incremental
      - name: Build Image
        run: |
          . scripts/func.sh

          echo "Create Arc Image"
          IMAGE_FILE="arc.img"
          gzip -dc "files/initrd/opt/arc/grub.img.gz" >"${IMAGE_FILE}"
          fdisk -l "${IMAGE_FILE}"
          
          LOOPX=$(sudo losetup -f)
          sudo losetup -P "${LOOPX}" "${IMAGE_FILE}"

          echo "Mounting Image File"
          mkdir -p "/tmp/p1"
          mkdir -p "/tmp/p3"
          sudo mount ${LOOPX}p1 "/tmp/p1"
          sudo mount ${LOOPX}p3 "/tmp/p3"

          [ ! -f "br/bzImage-arc" ] || [ ! -f "br/initrd-arc" ] && return 1
          
          echo "Repack initrd"
          cp -f "br/bzImage-arc" "files/p3/bzImage-arc"
          repackInitrd "br/initrd-arc" "files/initrd" "files/p3/initrd-arc"

          echo "Copying files"
          sudo cp -Rf "files/p1/"* "/tmp/p1"
          sudo cp -Rf "files/p3/"* "/tmp/p3"
          sync

          echo "Unmount image file"
          sudo umount "/tmp/p1"
          sudo umount "/tmp/p3"
          rmdir "/tmp/p1"
          rmdir "/tmp/p3"

          sudo losetup --detach ${LOOPX}

          #resizeImg "arc.img" "+1024M" "arc-2G.img"
          #mv -f "arc-2G.img" "arc.img"

          echo "Image Converter"
          #qemu-img convert arc.img -O vmdk -o adapter_type=lsilogic,compat6 arc-dyn.vmdk
          #qemu-img convert arc.img -O vmdk -o adapter_type=lsilogic,subformat=monolithicFlat,compat6 arc.vmdk
          #qemu-img convert arc.img -O vhdx -o subformat=dynamic arc.vhdx

          #echo "Create Arc ova"
          #convertova "arc.img" "arc.ova"

      # Zip image and generate checksum
      - name: Pack
        run: |
          #if [ -n "${{ env.VERSION }}" ]; then
          zip -9 "arc-${GITHUB_SHA::7}.img.zip" arc.img
          #  zip -9 "arc-${{ env.VERSION }}.vmdk-dyn.zip" arc-dyn.vmdk
          #  zip -9 "arc-${{ env.VERSION }}.vmdk-flat.zip" arc.vmdk arc-flat.vmdk
          #  zip -9 "arc-${{ env.VERSION }}.vhdx.zip" arc.vhdx
          #  zip -9 "arc-${{ env.VERSION }}.ova.zip" arc.ova
          #else
          #zip -9 "arc.img.zip" arc.img
          #fi
          zip -9j update.zip "files/p3/bzImage-arc" "files/p3/initrd-arc" "files/p1/ARC-VERSION" "files/p1/boot/grub/grub.cfg"
          sha256sum update.zip >checksum.sha256

      # Upload artifact
      - name: Upload
        if: success() && env.VERSION != ''
        uses: actions/upload-artifact@v4
        with:
          name: Images
          path: |
            arc-*.img.zip
            update.zip
            checksum.sha256
          retention-days: 2
